### ISSUE TITLE
Localization checklist

### ISSUE THREAD

**Issue by janklimo** [pickle-finance/pickle-ui#151]
Here's a list of files we're working with. I'll use it to track progress of which ones are i18n-ready (all strings fetched from locale files).

For future reference, output of:

```
find ./components ./features ./pages -type f -exec stat -f "- [ ] \`%N\`" {} \;
```

- [x] `./components/TokenIcon.tsx`
- [x] `./components/Brining.js` ❌ _removed_
- [x] `./components/JarValueChart.js`
- [x] `./components/EarnRow.js` 
- [x] `./components/ThemedTable.js` 
- [x] `./components/DayPicker.tsx`
- [x] `./components/JarPerformanceChart.js`
- [x] `./components/Support.js` ❌ _removed_
- [x] `./components/SelectPeriod.tsx` ❌ _removed_
- [x] `./components/PercentageInput.tsx`
- [x] `./components/Dashboard.js` ❌ _removed_
- [x] `./components/InfoCardContent.js`
- [x] `./components/PickleIcon.tsx`
- [x] `./features/Footer/Footer.tsx`
- [x] `./features/Prices/Prices.tsx`
- [x] `./features/Connection/types.d.ts`
- [x] `./features/Connection/MobileNetworkIndicator.tsx`
- [x] `./features/Connection/Web3Modal/index.js`
- [x] `./features/Connection/Web3Modal/useEagerConnect.js`
- [x] `./features/Connection/Web3Modal/ConnectorItem.tsx`
- [x] `./features/Connection/Web3Modal/Web3Modal.tsx`
- [x] `./features/Connection/Web3Modal/Connectors.ts`
- [x] `./features/Connection/DesktopNetworkIndicator.tsx`
- [x] `./features/Connection/MobileConnect.tsx`
- [x] `./features/Connection/DesktopConnect.tsx`
- [x] `./features/Zap/DepositZap.tsx`
- [x] `./features/Zap/tokens.tsx`
- [x] `./features/Zap/useBalance.ts`
- [x] `./features/Zap/useInfoAPYs.ts` ❌ _removed_
- [x] `./features/Zap/useExitToToken.ts` ❌ _removed_
- [x] `./features/Zap/Info.tsx` ❌ _removed_
- [x] `./features/Zap/Deposit.tsx` ❌ _removed_
- [x] `./features/Zap/ExitToToken.tsx` ❌ _removed_
- [x] `./features/Zap/Withdraw.tsx` ❌ _removed_
- [x] `./features/Zap/useZapper.tsx`
- [x] `./features/Zap/ExitToJar.tsx` ❌ _removed_
- [x] `./features/Zap/useFarmBalances.ts` ❌ _removed_
- [x] `./features/Zap/getAPYTooltip.tsx` ❌ _removed_
- [x] `./features/Zap/farms.ts` ❌ _removed_
- [x] `./features/Zap/useExitToJar.ts` ❌ _removed_
- [x] `./features/Zap/constants.ts`
- [x] `./features/Zap/useDeposit.ts` ❌ _removed_
- [x] `./features/InfoBar/InfoBar.tsx`
- [x] `./features/MasterchefV2/MC2Farm.tsx`
- [x] `./features/Farms/UseMigrate.ts`
- [x] `./features/Farms/SummaryCard.tsx` ❌ _removed_
- [x] `./features/Farms/FarmList.tsx`
- [x] `./features/Farms/FarmCollapsible.tsx` only used on old-farms page
- [x] `./features/Collapsible/Expand.tsx`
- [x] `./features/Collapsible/useRealShape.ts`
- [x] `./features/Collapsible/Collapse.tsx`
- [x] `./features/Collapsible/withDefaults.ts`
- [x] `./features/Collapsible/CollapseIcon.tsx`
- [x] `./features/Collapsible/CollapseContext.ts`
- [x] `./features/MiniFarms/MiniFarmList.tsx`
- [x] `./features/MiniFarms/MiniFarmCollapsible.tsx`
- [x] `./features/MiniFarms/JarMiniFarmCollapsible.tsx`
- [x] `./features/Balances/Balances.tsx`
- [x] `./features/Balances/usePendingPickles.ts`
- [x] `./features/Balances/useBalances.ts`
- [x] `./features/TopBar/TopBar.tsx`
- [x] `./features/TopBar/Logo.tsx`
- [x] `./features/TopBar/NavItems.tsx`
- [x] `./features/Gauges/VoteCollapsible.tsx`
- [x] `./features/Gauges/BProtocol.tsx`
- [x] `./features/Gauges/GaugeList.tsx`
- [x] `./features/Gauges/useJarData.ts`
- [x] `./features/Gauges/JarGaugeCollapsible.tsx`
- [x] `./features/Gauges/SummaryCard.tsx` ❌ _removed_
- [x] `./features/Gauges/GaugeChartCollapsible.tsx`
- [x] `./features/Gauges/GaugeInfo.js`
- [x] `./features/Gauges/GaugeCollapsible.tsx`
- [x] `./features/DILL/Balances.tsx`
- [x] `./features/DILL/Claim.tsx`
- [x] `./features/DILL/CalcCollapsible.tsx`
- [x] `./features/DILL/FeeDistributionsChart.tsx`
- [x] `./features/DILL/Lock/IncreaseTime.tsx`
- [x] `./features/DILL/Lock/Withdraw.tsx`
- [x] `./features/DILL/Lock/IncreaseAmount.tsx`
- [x] `./features/DILL/Lock/CreateLock.tsx`
- [x] `./features/DILL/Lock/LockDurationChart.tsx`
- [x] `./features/DILL/DillStats.tsx`
- [x] `./features/DILL/DILL.tsx`
- [x] `./features/DILL/Interaction.tsx`
- [x] `./pages/index.tsx`
- [x] `./features/PickleFarms/BalFarm.tsx`
- [x] `./pages/info.tsx`
- [x] `./pages/_document.tsx`
- [x] `./pages/info/jars.js`
- [x] `./pages/info/earn.js`
- [x] `./pages/info/stats.js`
- [x] `./pages/dill.tsx`
- [x] `./pages/_app.tsx`
- [x] `./pages/farms.tsx`
- [x] `./pages/old-farms.tsx`

**Comment by janklimo** [comment]
@larrythecucumber321 spotted 11 files we can remove. Can you see more? We can remove them before anything else. Thanks!

**Comment by larrythecucumber321** [comment]
@janklimo Nice list! I doubled checked the items you flagged for removal and they're indeed good to go. Did you try using a tool such as the ones mentioned here? https://stackoverflow.com/a/61488662 Otherwise, I have no additional input :)
